version: '3.8'
services:
  backend:
    build: .
    container_name: nextedge-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nextedge
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo
    volumes:
      - .env:/app/.env
  mongo:
    image: mongo:6.0
    container_name: nextedge-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 