version: '3.8'
services:
  backend:
    build: .
    container_name: nextedge-backend-dev
    command: npx ts-node-dev --respawn --transpile-only src/index.ts
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nextedge
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
      - .env:/app/.env
  mongo:
    image: mongo:6.0
    container_name: nextedge-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db
volumes:
  mongo_data_dev: 